import { NextResponse } from 'next/server'; import { getServerSession } from 'next-auth'; import { authOptions } from '@/lib/auth'; import { prisma } from '@/lib/prisma'; import { publishOrderEvent } from '@/lib/order-events'; import { sendCustomerStatusEmail } from '@/lib/email'; import { decrypt } from '@/lib/crypto'; import { orderForClient } from '@/lib/order-view'; import { queueAndSendOrderWhatsApp } from '@/lib/whatsapp';
async function guard(){const s=await getServerSession(authOptions);const id=(s?.user as any)?.id;if(!id)return false;return (await prisma.user.findUnique({where:{id},select:{role:true}}))?.role==='ADMIN'}
export async function GET(){if(!(await guard()))return NextResponse.json({error:'Unauthorized'},{status:401});const orders=await prisma.order.findMany({include:{items:true},orderBy:{createdAt:'desc'},take:500});const today=new Date();today.setHours(0,0,0,0);const todays=orders.filter(o=>o.createdAt>=today);const revenue=todays.filter(o=>o.status==='COMPLETED').reduce((a,o)=>a+o.total,0);const counts=new Map<string,number>();todays.forEach(o=>o.items.forEach(i=>counts.set(i.name,(counts.get(i.name)||0)+i.quantity)));return NextResponse.json({orders:orders.map(o=>orderForClient(o,true)),revenue,volume:todays.length,completedVolume:todays.filter(o=>o.status==='COMPLETED').length,top:Array.from(counts.entries()).sort((a,b)=>b[1]-a[1]).slice(0,5)});}
export async function PATCH(req:Request){
 if(!(await guard()))return NextResponse.json({error:'Unauthorized'},{status:401}); const {id,status}=await req.json(); if(!['RECEIVED','BREWING','PACKED','COMPLETED','REJECTED'].includes(status))return NextResponse.json({error:'Invalid status'},{status:400});
 const existing=await prisma.order.findUnique({where:{id},include:{items:true}}); if(!existing)return NextResponse.json({error:'Order not found'},{status:404});
 if(existing.status===status)return NextResponse.json(orderForClient(existing,true));
 const allowed:Record<string,string[]>={RECEIVED:['BREWING','REJECTED'],BREWING:['PACKED','REJECTED'],PACKED:['COMPLETED','REJECTED'],COMPLETED:[],REJECTED:[]}; if(!allowed[existing.status]?.includes(status))return NextResponse.json({error:`Cannot move ${existing.status} to ${status}.`},{status:400});
 const order=await prisma.order.update({where:{id},data:{status,paymentStatus:status==='COMPLETED'&&existing.paymentMethod==='CASH'?'PAID':existing.paymentStatus},include:{items:true}});
 const customerName=decrypt(order.customerNameEncrypted)||'Customer',customerPhone=decrypt(order.customerPhoneEncrypted)||'',customerEmail=decrypt(order.customerEmailEncrypted)||'';
 publishOrderEvent({type:'ORDER_STATUS_CHANGED',orderId:order.id,status:order.status,createdAt:order.createdAt.toISOString(),customerName,total:order.total,paymentMethod:order.paymentMethod});
 if(status!=='REJECTED'){await Promise.allSettled([sendCustomerStatusEmail({orderId:order.id,customerName,customerEmail,status:status as any,fulfillmentType:order.fulfillmentType,total:order.total}),status==='PACKED'?queueAndSendOrderWhatsApp({orderId:order.id,phone:customerPhone,name:customerName,total:order.total,status:'PREPARED'}):status==='COMPLETED'?queueAndSendOrderWhatsApp({orderId:order.id,phone:customerPhone,name:customerName,total:order.total,status:'READY'}):Promise.resolve(false)]);}
 return NextResponse.json(orderForClient(order,true));
}
