'use client';
import {useEffect,useRef,useState} from 'react';
import {useSession} from 'next-auth/react';
import {BarChart3,Coffee,Mail,PackageCheck,Phone,RefreshCw,Truck,Building2,WalletCards,ArrowRight,Bell,Volume2} from 'lucide-react';
import {OrderStatus} from '@/types';
const statuses:OrderStatus[]=['RECEIVED','BREWING','PACKED','COMPLETED'];

export default function Admin(){
 const{data:session,status}=useSession();const[data,setData]=useState<any>(null);const[error,setError]=useState('');const[notice,setNotice]=useState<any>(null);const audioRef=useRef<AudioContext|null>(null);
 const load=async()=>{const r=await fetch('/api/admin/orders',{cache:'no-store'});if(!r.ok){setError('Admin access required.');return}setError('');setData(await r.json())};
 const ding=()=>{try{const Ctx=window.AudioContext||(window as any).webkitAudioContext;if(!Ctx)return;audioRef.current ||= new Ctx();const ctx=audioRef.current;const now=ctx.currentTime;[0,0.14,0.28].forEach((delay,i)=>{const osc=ctx.createOscillator();const gain=ctx.createGain();osc.frequency.value=i===1?880:660;gain.gain.setValueAtTime(0.0001,now+delay);gain.gain.exponentialRampToValueAtTime(0.12,now+delay+0.01);gain.gain.exponentialRampToValueAtTime(0.0001,now+delay+0.11);osc.connect(gain);gain.connect(ctx.destination);osc.start(now+delay);osc.stop(now+delay+0.12)})}catch{}}
 const browserNotify=(title:string,body:string)=>{if(typeof Notification!=='undefined'&&Notification.permission==='granted')new Notification(title,{body,icon:'/favicon.ico'})};
 useEffect(()=>{if((session?.user as any)?.role!=='ADMIN')return;load();if(typeof Notification!=='undefined'&&Notification.permission==='default')Notification.requestPermission();const es=new EventSource('/api/admin/orders/stream');es.onmessage=(e)=>{try{const ev=JSON.parse(e.data);if(ev.type==='ORDER_CREATED'){setNotice(ev);ding();browserNotify(`New Oat & Ember order #${ev.orderId.slice(-6).toUpperCase()}`,`${ev.customerName||'Customer'} · ₹${ev.total||0} · ${ev.paymentMethod==='CASH'?'Cash due':'Razorpay paid'}`);load()}else if(ev.type==='ORDER_STATUS_CHANGED')load()}catch{}};es.onerror=()=>{};return()=>es.close()},[session]);
 if(status==='loading')return <main className="min-h-screen p-6 text-oat/50">Loading ops room…</main>;
 if(!session||((session.user as any).role!=='ADMIN'))return <main className="grid min-h-[calc(100svh-72px)] place-items-center px-5 text-center"><div><span className="eyebrow text-matcha">Restricted floor</span><h1 className="display mt-3 text-5xl font-black">Ops room locked.</h1><p className="mt-3 text-oat/45">Sign in with the café admin account.</p></div></main>;
 const orders=data?.orders||[];return <main className="grain min-h-[calc(100svh-72px)]"><div className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 md:px-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><span className="eyebrow text-matcha">Oat & Ember / live floor</span><h1 className="display mt-2 text-5xl font-black tracking-[-.05em] sm:text-6xl">Control room.</h1><p className="mt-2 flex items-center gap-2 text-sm text-oat/35"><span className="h-2 w-2 animate-pulse rounded-full bg-matcha"/> Live order alerts are on.</p></div><div className="flex gap-2"><button onClick={ding} className="flex items-center justify-center gap-2 rounded-full border border-white/10 bg-white/[.04] px-4 py-2.5 text-xs font-black"><Volume2 size={14}/> Test alert</button><button onClick={load} className="flex items-center justify-center gap-2 rounded-full border border-white/10 bg-white/[.04] px-4 py-2.5 text-xs font-black"><RefreshCw size={14}/> Refresh</button></div></div>
 {notice&&<button onClick={()=>setNotice(null)} className="mt-5 flex w-full items-center gap-3 rounded-2xl border border-terracotta/25 bg-terracotta/10 p-4 text-left"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-terracotta text-white"><Bell size={18}/></div><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[.2em] text-terracotta">New order</p><p className="mt-1 truncate text-sm font-black">#{notice.orderId.slice(-6).toUpperCase()} · {notice.customerName} · ₹{notice.total}</p></div><span className="ml-auto text-[10px] font-black text-oat/35">Click to dismiss</span></button>}
 <div className="mt-7 grid gap-3 sm:grid-cols-3"><Metric icon={<BarChart3/>} label="Today's revenue" value={`₹${data?.revenue||0}`}/><Metric icon={<Coffee/>} label="Order volume" value={data?.volume||0}/><Metric icon={<PackageCheck/>} label="Top seller" value={data?.top?.[0]?.[0]||'—'}/></div>{error&&<p className="mt-4 rounded-2xl bg-terracotta/10 p-3 text-sm text-terracotta">{error}</p>}<div className="mt-8 overflow-x-auto pb-4 no-scrollbar"><div className="grid min-w-[1180px] grid-cols-4 gap-3">{statuses.map(s=><section key={s} className="min-h-[520px] rounded-[1.7rem] border border-white/10 bg-white/[.025] p-3"><div className="mb-3 flex items-center justify-between rounded-2xl bg-white/[.035] px-3 py-3"><div><p className="eyebrow text-oat/30">Lane {String(statuses.indexOf(s)+1).padStart(2,'0')}</p><h2 className="mt-1 text-xs font-black tracking-[.15em]">{s}</h2></div><span className="grid h-8 min-w-8 place-items-center rounded-full bg-white/10 px-2 text-[10px] font-black">{orders.filter((o:any)=>o.status===s).length}</span></div><div className="space-y-3">{orders.filter((o:any)=>o.status===s).map((o:any)=><Ticket key={o.id} order={o} onStatus={async(st:OrderStatus)=>{const r=await fetch('/api/admin/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:o.id,status:st})});if(!r.ok){const d=await r.json();setError(d.error||'Unable to update order.');return}load()}}/>)}</div></section>)}</div></div></div></main>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:any}){return <div className="rounded-[1.5rem] border border-white/10 bg-white/[.035] p-5"><div className="flex items-center gap-2 text-matcha">{icon}<span className="eyebrow text-oat/35">{label}</span></div><strong className="display mt-3 block text-3xl font-black">{value}</strong></div>}
function Ticket({order,onStatus}:{order:any;onStatus:(s:OrderStatus)=>void}){const next=statuses[statuses.indexOf(order.status)+1];let fd:any={};try{fd=JSON.parse(order.fulfillmentData)}catch{}const vehicle=order.fulfillmentType==='VEHICLE';return <article className="rounded-[1.4rem] border border-white/10 bg-[#211c18] p-4"><div className="flex items-start justify-between gap-3"><div><span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[8px] font-black tracking-wider ${vehicle?'bg-terracotta/15 text-terracotta':'bg-matcha/15 text-matcha'}`}>{vehicle?<Truck size={10}/>:<Building2 size={10}/>} {vehicle?'VEHICLE':'OFFICE'}</span><h3 className="mt-2 font-bold">{order.customerName}</h3><p className="text-[10px] text-oat/30">#{order.id.slice(-6).toUpperCase()} · {new Date(order.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</p></div><b className="text-terracotta">₹{order.total}</b></div><div className="mt-3 flex gap-2"><a href={`tel:+91${order.customerPhone}`} className="inline-flex items-center gap-1 rounded-full bg-matcha/10 px-2.5 py-1.5 text-[9px] font-black text-matcha"><Phone size={10}/> Call</a><a href={`mailto:${order.customerEmail}`} className="inline-flex items-center gap-1 rounded-full bg-white/5 px-2.5 py-1.5 text-[9px] font-black text-oat/55"><Mail size={10}/> Email</a></div><div className="my-3 space-y-1 border-y border-white/5 py-3 text-[11px] text-oat/55">{order.items.map((i:any)=><div key={i.id} className="flex justify-between"><span>{i.quantity}× {i.name}</span><span>₹{i.unitPrice*i.quantity}</span></div>)}</div><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-wider"><WalletCards size={12} className={order.paymentMethod==='CASH'?'text-terracotta':'text-matcha'}/><span className={order.paymentMethod==='CASH'?'text-terracotta':'text-matcha'}>{order.paymentMethod==='CASH'?'Cash due':'Razorpay paid'}</span></div><p className="mt-2 text-[10px] leading-4 text-oat/30">{vehicle?`${fd.vehicleType||''} · ${fd.color||''} · ${fd.licensePlate||''} · ${fd.arrivalTime||''}`:`${fd.companyName||''} · ${fd.floorRoomBuilding||''} · ${fd.contactPerson||''}`}</p>{next&&<button onClick={()=>onStatus(next)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-oat py-2.5 text-[10px] font-black text-espresso">Move to {next}<ArrowRight size={13}/></button>}</article>}
