'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowDown,ArrowRight,ArrowUpRight,Bike,Building2,Car,Clock3,Coffee,MapPin,Sparkles,Truck,Zap,ShoppingBag} from 'lucide-react';
import {motion} from 'framer-motion';
import MenuCard from '@/components/MenuCard';
import CustomizerModal from '@/components/CustomizerModal';
import TakeawaySelectorModal from '@/components/TakeawaySelectorModal';
import {Product} from '@/types';
import {useCart} from '@/store/cart';

export default function Home(){
 const [products,setProducts]=useState<Product[]>([]);const [cats,setCats]=useState<string[]>([]);const [cat,setCat]=useState('All');const [selected,setSelected]=useState<Product|null>(null);const [pick,setPick]=useState(false);const setOpen=useCart(s=>s.setOpen);
 useEffect(()=>{fetch('/api/products').then(r=>r.json()).then(d=>{setProducts(d.products||[]);setCats(d.categories||[])})},[]);
 const visible=useMemo(()=>products.filter(p=>cat==='All'||p.category===cat),[products,cat]);
 return <main className="grain">
  <section className="hero-grid relative overflow-hidden border-b border-white/[.08]">
   <div className="absolute left-[55%] top-[-10%] h-[420px] w-[420px] rounded-full bg-terracotta/15 blur-[110px]"/><div className="absolute bottom-[-10%] left-[-5%] h-[360px] w-[360px] rounded-full bg-matcha/10 blur-[100px]"/>
   <div className="mx-auto grid min-h-[calc(100svh-72px)] max-w-[1440px] items-center gap-8 px-4 py-8 sm:px-6 md:grid-cols-[1.1fr_.9fr] md:gap-12 md:px-8 md:py-14 lg:min-h-[720px]">
    <div className="relative z-10">
      <div className="flex flex-wrap items-center gap-2"><span className="eyebrow rounded-full border border-matcha/25 bg-matcha/10 px-3 py-2 text-matcha">Surat · open 7am–10pm</span><span className="eyebrow rounded-full border border-white/10 bg-white/[.04] px-3 py-2 text-oat/40">no queue energy</span></div>
      <motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="display mt-7 max-w-5xl text-[4.25rem] font-black leading-[.82] tracking-[-.075em] sm:text-[6.5rem] lg:text-[8.4rem]">COFFEE<br/><span className="text-terracotta">ON YOUR</span><br/>TERMS.</motion.h1>
      <p className="mt-7 max-w-xl text-base leading-7 text-oat/50 sm:text-lg">Small-batch coffee, pastries and matcha made for people who are already halfway out the door.</p>
      <div className="mt-7 grid grid-cols-2 gap-2 sm:flex sm:flex-wrap"><a href="#menu" className="btn flex items-center justify-center gap-2 rounded-2xl bg-oat px-5 py-4 text-sm font-black text-espresso">Shop the menu <ArrowDown size={16}/></a><button onClick={()=>setPick(true)} className="btn flex items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/[.04] px-5 py-4 text-sm font-black">Choose handover <ArrowUpRight size={16}/></button></div>
      <div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-[11px] font-bold text-oat/35"><span className="flex items-center gap-1.5"><MapPin size={13} className="text-matcha"/> Surat</span><span>•</span><span className="flex items-center gap-1.5"><Clock3 size={13} className="text-terracotta"/> 10–20 min pickup</span><span>•</span><span>Receipts by email</span></div>
    </div>
    <div className="relative mx-auto w-full max-w-[560px] md:rotate-2">
      <div className="absolute -left-2 top-5 z-20 w-44 rotate-[-7deg] rounded-2xl border border-white/10 bg-[#191512]/90 p-4 shadow-2xl backdrop-blur-xl sm:-left-7"><div className="flex items-center justify-between"><span className="eyebrow text-matcha">Drop #01</span><Zap size={14} className="text-terracotta"/></div><p className="display mt-2 text-xl font-black">First sip energy.</p><p className="mt-1 text-[11px] text-oat/35">Cold brew · 6:58 AM</p></div>
      <div className="relative overflow-hidden rounded-[2.2rem] border border-white/10 bg-[#211c18] p-2.5 shadow-editorial sm:rounded-[3rem] sm:p-3"><img src="https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1400&q=90" alt="Warm modern café" className="aspect-[.82] w-full rounded-[1.8rem] object-cover sm:rounded-[2.5rem]"/><div className="absolute inset-x-7 bottom-7 rounded-[1.5rem] border border-white/15 bg-[#0e0c0b]/78 p-4 backdrop-blur-xl sm:inset-x-8 sm:bottom-8 sm:p-5"><div className="flex items-center justify-between"><span className="eyebrow text-oat/35">Today at O&E</span><span className="text-[10px] font-black text-matcha">● OPEN</span></div><div className="mt-2 flex items-end justify-between gap-3"><p className="display max-w-xs text-2xl font-black leading-none sm:text-3xl">Your usual,<br/>but faster.</p><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-terracotta"><ArrowUpRight size={18}/></span></div></div></div>
    </div>
   </div>
   <div className="border-y border-white/[.07] bg-white/[.025] py-3"><motion.div animate={{x:[0,-500]}} transition={{repeat:Infinity,duration:22,ease:'linear'}} className="flex w-max gap-7 whitespace-nowrap text-[9px] font-black uppercase tracking-[.3em] text-oat/25"><span>CURBSIDE WITHOUT THE QUEUE</span><span>✦</span><span>OFFICE COFFEE WITHOUT THE CHAOS</span><span>✦</span><span>RECEIPTS STRAIGHT TO INBOX</span><span>✦</span><span>CURBSIDE WITHOUT THE QUEUE</span><span>✦</span></motion.div></div>
  </section>

  <section className="mx-auto max-w-[1440px] px-4 py-10 sm:px-6 md:px-8 md:py-16"><div className="grid gap-3 md:grid-cols-3"><Feature num="01" icon={<Truck/>} title="Window service" text="Park. Text nothing. We bring the bag to your window."/><Feature num="02" icon={<Building2/>} title="Office mode" text="Send the whole round upstairs with room-ready handover details."/><Feature num="03" icon={<Clock3/>} title="Timed to you" text="Choose your arrival window and keep moving."/></div></section>

  <section id="menu" className="scroll-mt-20 border-y border-white/[.07] bg-[#f0e4dc] text-espresso"><div className="mx-auto max-w-[1440px] px-4 py-12 sm:px-6 md:px-8 md:py-20"><div className="grid gap-8 md:grid-cols-[.8fr_1.2fr] md:items-end"><div><p className="eyebrow text-terracotta">The drop menu</p><h2 className="display mt-3 text-5xl font-black leading-[.88] tracking-[-.05em] sm:text-6xl lg:text-7xl">Pick your<br/><span className="text-terracotta">personality.</span></h2><p className="mt-5 max-w-lg text-sm leading-6 text-espresso/55">Cold, bold, sweet, green, or dangerously pastry-shaped. Customize it before it hits your bag.</p></div><div className="flex gap-2 overflow-x-auto pb-1 no-scrollbar md:justify-end">{['All',...cats.filter(c=>c!=='All')].map(c=><button key={c} onClick={()=>setCat(c)} className={`whitespace-nowrap rounded-full border px-4 py-2.5 text-[10px] font-black uppercase tracking-wider transition ${cat===c?'border-espresso bg-espresso text-oat':'border-espresso/15 bg-transparent text-espresso/55 hover:border-espresso/35'}`}>{c}</button>)}</div></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map((p,i)=><MenuCard key={p.id} product={p} onCustomize={setSelected} index={i}/>)}</div></div></section>

  <section id="lanes" className="scroll-mt-20 mx-auto max-w-[1440px] px-4 py-12 sm:px-6 md:px-8 md:py-20"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow text-matcha">Choose your exit</p><h2 className="display mt-2 text-5xl font-black tracking-[-.05em] sm:text-6xl">Two lanes.<br/>One good order.</h2></div><p className="max-w-md text-sm leading-6 text-oat/40">No dull forms. Tell the barista what they need to know, then we do the rest.</p></div><div className="mt-8 grid gap-4 lg:grid-cols-2"><Lane type="VEHICLE" icon={<Car/>} title="Pull up. We pull up." text="Car or bike, colour, plate and arrival window. Your coffee goes to your window." onClick={()=>setPick(true)}/><Lane type="CORPORATE" icon={<Building2/>} title="Send it upstairs." text="Company, floor, room, contact person and group notes. Built for office rounds." onClick={()=>setPick(true)}/></div></section>

  <section className="mx-auto max-w-[1440px] px-4 pb-20 sm:px-6 md:px-8"><div className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-[#1a1613] p-6 sm:p-8 md:p-12"><div className="absolute right-[-10%] top-[-50%] h-[420px] w-[420px] rounded-full bg-terracotta/15 blur-[100px]"/><div className="relative grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><span className="eyebrow text-terracotta">No sad coffee breaks</span><h2 className="display mt-3 max-w-3xl text-4xl font-black leading-[.95] sm:text-5xl md:text-6xl">Build the order. Choose the exit. Keep your day moving.</h2></div><button onClick={()=>setOpen(true)} className="btn flex items-center justify-center gap-2 rounded-2xl bg-terracotta px-6 py-4 text-sm font-black">Open my bag <ShoppingBagIcon/></button></div></div></section>

  <CustomizerModal product={selected} onClose={()=>setSelected(null)}/>{pick&&<TakeawaySelectorModal onClose={()=>setPick(false)} onSelect={()=>{setPick(false);setOpen(true)}}/>}
 </main>
}
function Feature({num,icon,title,text}:{num:string;icon:React.ReactNode;title:string;text:string}){return <motion.div whileHover={{y:-5}} className="group relative overflow-hidden rounded-[1.7rem] border border-white/10 bg-white/[.035] p-6"><span className="absolute right-5 top-5 display text-4xl font-black text-white/[.06]">{num}</span><div className="grid h-11 w-11 place-items-center rounded-2xl bg-oat text-espresso transition group-hover:rotate-3 group-hover:bg-terracotta group-hover:text-white">{icon}</div><h3 className="display mt-6 text-2xl font-black">{title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-oat/40">{text}</p></motion.div>}
function Lane({type,icon,title,text,onClick}:{type:string;icon:React.ReactNode;title:string;text:string;onClick:()=>void}){return <button onClick={onClick} className="group relative overflow-hidden rounded-[2rem] border border-white/10 bg-white/[.035] p-6 text-left transition hover:-translate-y-1 hover:bg-white/[.055] sm:p-8"><div className="absolute right-[-30px] top-[-30px] h-40 w-40 rounded-full bg-matcha/10 blur-3xl"/><div className="relative flex items-start justify-between gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-matcha text-espresso">{icon}</span><ArrowUpRight className="text-oat/30 transition group-hover:translate-x-1 group-hover:-translate-y-1"/></div><p className="eyebrow mt-8 text-matcha">{type==='VEHICLE'?'CURBSIDE':'CORPORATE'}</p><h3 className="display mt-2 text-3xl font-black sm:text-4xl">{title}</h3><p className="mt-3 max-w-xl text-sm leading-6 text-oat/45">{text}</p><span className="mt-7 inline-flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-xs font-black">Set this handover <ArrowRight size={14}/></span></button>}
function ShoppingBagIcon(){return <ShoppingBag size={16}/>} 
