'use client';
import Link from 'next/link';
import { ArrowRight, Clock3, MapPin, ShoppingBag, Star, ChevronLeft, ChevronRight, Sparkles, ReceiptText } from 'lucide-react';
import { motion } from 'framer-motion';
import { useEffect, useState } from 'react';
import { useCart } from '@/store/cart';
import { Product } from '@/types';

const fallbackReviews = [
  ['Riya Shah','The pickup flow is ridiculously smooth. I order before leaving and the coffee is ready when I reach.'],
  ['Kunal Mehta','Finally a café site that feels designed for ordering, not just looking pretty.'],
  ['Anaya Patel','The menu is simple, the customisations make sense, and reordering is super quick.'],
  ['Meera Joshi','The receipt looks so good I actually saved it. Tiny detail, huge difference.'],
] as const;

const fallback: Product[] = [
  {id:'demo-1',name:'Cold Brew',slug:'cold-brew',description:'Slow-steeped, chocolatey and ice-cold.',category:'Cold Coffee',price:190,image:'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=85',available:true},
  {id:'demo-2',name:'Flat White',slug:'flat-white',description:'Silky microfoam with a double espresso base.',category:'Coffee',price:180,image:'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=85',available:true},
  {id:'demo-3',name:'Matcha Cloud',slug:'matcha-cloud',description:'Ceremonial matcha with vanilla foam.',category:'Matcha',price:220,image:'/images/matcha-cloud.svg',available:true},
  {id:'demo-4',name:'Cinnamon Roll',slug:'cinnamon-roll',description:'Warm, sticky, buttery and unapologetically gooey.',category:'Pastries',price:160,image:'https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&w=900&q=85',available:true},
];

export default function Home(){
 const setOpen=useCart(s=>s.setOpen); const [products,setProducts]=useState<Product[]>(fallback); const [reviews,setReviews]=useState<readonly (readonly [string,string])[]>(fallbackReviews); const [review,setReview]=useState(0);
 useEffect(()=>{fetch('/api/products',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(d.products?.length)setProducts(d.products.slice(0,4))}).catch(()=>{}); fetch('/api/testimonials',{cache:'no-store'}).then(r=>r.json()).then(d=>{const rows=Array.isArray(d.testimonials)?d.testimonials:[]; if(rows.length)setReviews(rows.map((x:any)=>[String(x.name||'O&E Regular'),String(x.text||'')]).filter((x:any)=>x[1]))}).catch(()=>{})},[]);
 useEffect(()=>{const t=setInterval(()=>setReview(v=>(v+1)%reviews.length),5000);return()=>clearInterval(t)},[]);
 return <main className="grain">
  <section className="relative overflow-hidden border-b border-white/10">
   <div className="absolute inset-0 hero-grid opacity-60"/><div className="absolute -right-20 -top-32 h-96 w-96 rounded-full bg-terracotta/15 blur-[100px]"/><div className="absolute -bottom-40 left-0 h-96 w-96 rounded-full bg-matcha/10 blur-[110px]"/>
   <div className="relative mx-auto grid min-h-[calc(100svh-72px)] max-w-[1440px] items-center gap-10 px-4 py-10 sm:px-6 md:grid-cols-[1.05fr_.95fr] md:px-8 lg:py-16">
    <div>
      <div className="flex flex-wrap gap-2"><span className="eyebrow rounded-full border border-matcha/25 bg-matcha/10 px-3 py-2 text-matcha">Surat · takeaway first</span><span className="eyebrow rounded-full border border-white/10 bg-white/[.04] px-3 py-2 text-oat/40">ready in 10–20 min</span></div>
      <motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="display mt-7 max-w-4xl text-[4.3rem] font-black leading-[.82] tracking-[-.075em] sm:text-[6.7rem] lg:text-[8.5rem]">GOOD<br/><span className="text-terracotta">COFFEE.</span><br/>NO QUEUE.</motion.h1>
      <p className="mt-7 max-w-xl text-base leading-7 text-oat/50 sm:text-lg">Order ahead, choose your pickup moment, and keep moving. A premium café experience built around the way Surat actually orders.</p>
      <div className="mt-7 flex flex-col gap-2 sm:flex-row"><Link href="/menu" className="btn inline-flex items-center justify-center gap-2 rounded-2xl bg-oat px-6 py-4 text-sm font-black text-espresso">Order pickup <ArrowRight size={16}/></Link><button onClick={()=>setOpen(true)} className="btn inline-flex items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/[.04] px-6 py-4 text-sm font-black">Open bag <ShoppingBag size={16}/></button></div>
      <div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-[11px] font-bold text-oat/35"><span className="inline-flex items-center gap-1.5"><MapPin size={13} className="text-matcha"/> Vesu · Surat</span><span className="inline-flex items-center gap-1.5"><Clock3 size={13} className="text-terracotta"/> Pickup 7am–10pm</span><span className="inline-flex items-center gap-1.5"><ReceiptText size={13}/> Branded digital receipts</span></div>
    </div>
    <div className="relative mx-auto w-full max-w-[560px] md:rotate-2"><div className="absolute -left-2 top-5 z-10 w-44 rotate-[-7deg] rounded-2xl border border-white/10 bg-[#191512]/90 p-4 shadow-2xl backdrop-blur-xl sm:-left-8"><span className="eyebrow text-matcha">Today’s pick</span><p className="display mt-2 text-xl font-black">Cold brew energy.</p><p className="mt-1 text-[11px] text-oat/35">Slow-steeped · ₹190</p></div><div className="overflow-hidden rounded-[2.4rem] border border-white/10 bg-[#211c18] p-2.5 shadow-editorial sm:p-3"><img src="https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1400&q=90" alt="Warm modern café interior" className="aspect-[.82] w-full rounded-[2rem] object-cover sm:rounded-[2.6rem]"/><div className="absolute inset-x-7 bottom-7 rounded-[1.5rem] border border-white/15 bg-[#0e0c0b]/80 p-4 backdrop-blur-xl sm:inset-x-8 sm:bottom-8 sm:p-5"><div className="flex items-center justify-between gap-3"><span className="eyebrow text-oat/35">Pickup ritual</span><span className="text-[10px] font-black text-matcha">● OPEN</span></div><p className="display mt-2 text-2xl font-black leading-none sm:text-3xl">Order it.<br/>Pick it up.</p></div></div></div>
   </div>
  </section>

  <section className="mx-auto max-w-[1440px] px-4 py-12 sm:px-6 md:px-8 md:py-16"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow text-terracotta">A taste of the menu</p><h2 className="display mt-2 text-4xl font-black sm:text-5xl">Keep it simple. Keep it good.</h2></div><Link href="/menu" className="hidden items-center gap-2 text-xs font-black text-matcha sm:inline-flex">Full menu <ArrowRight size={14}/></Link></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{products.map((p,i)=><Link href="/menu" key={p.id} className="group overflow-hidden rounded-[1.7rem] border border-white/10 bg-white/[.035]"><div className="aspect-[1.05] overflow-hidden"><img src={p.image} alt={p.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><span className="eyebrow text-oat/25">{p.category}</span><h3 className="mt-1 truncate text-lg font-black">{p.name}</h3></div><span className="shrink-0 font-black text-terracotta">₹{p.price}</span></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-oat/35">{p.description}</p></div></Link>)}</div><Link href="/menu" className="mt-5 flex items-center justify-center gap-2 rounded-2xl border border-white/10 py-3.5 text-xs font-black sm:hidden">View full menu <ArrowRight size={14}/></Link></section>

  <section className="mx-auto max-w-5xl px-4 pb-12 sm:px-6 md:pb-20"><div className="rounded-[2.2rem] border border-white/10 bg-[#1a1613] p-6 sm:p-9 md:p-12"><div className="flex items-start justify-between gap-5"><div><p className="eyebrow text-matcha">The regulars speak</p><h2 className="display mt-2 text-4xl font-black sm:text-5xl">Good coffee.<br/><span className="text-terracotta">Good word.</span></h2></div><Sparkles className="text-terracotta"/></div><motion.article key={review} initial={{opacity:0,x:16}} animate={{opacity:1,x:0}} className="mt-8 rounded-[1.7rem] border border-white/10 bg-white/[.035] p-6 sm:p-8"><div className="flex gap-1 text-terracotta">{Array.from({length:5}).map((_,i)=><Star key={i} size={15} fill="currentColor"/>)}</div><p className="mt-6 text-lg leading-8 text-oat/70 sm:text-2xl">“{reviews[review][1]}”</p><div className="mt-7 flex items-center justify-between gap-4"><span className="text-xs font-black uppercase tracking-wider text-oat/35">{reviews[review][0]} · O&E regular</span><div className="flex gap-2"><button onClick={()=>setReview(v=>(v-1+reviews.length)%reviews.length)} aria-label="Previous testimonial" className="grid h-10 w-10 place-items-center rounded-full border border-white/10"><ChevronLeft size={17}/></button><button onClick={()=>setReview(v=>(v+1)%reviews.length)} aria-label="Next testimonial" className="grid h-10 w-10 place-items-center rounded-full bg-oat text-espresso"><ChevronRight size={17}/></button></div></div></motion.article></div></section>

  <section className="mx-auto grid max-w-[1440px] gap-4 px-4 pb-20 sm:px-6 md:grid-cols-3 md:px-8"><Info title="Pickup, not waiting" text="Choose your handover details and arrive when your order is ready." icon={<Clock3/>}/><Info title="Your receipt, redesigned" text="Every order gets a branded receipt you can save from checkout or order history." icon={<ReceiptText/>}/><Info title="A café with a story" text="Meet the people, craft and little details behind the counter." icon={<Sparkles/>}/></section>
 </main>
}
function Info({title,text,icon}:{title:string;text:string;icon:React.ReactNode}){return <div className="rounded-[1.7rem] border border-white/10 bg-white/[.035] p-5 sm:p-6"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-terracotta/10 text-terracotta">{icon}</div><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-oat/40">{text}</p></div>}
